# Generated by Django 3.0.5 on 2022-04-03 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_salary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
