# Generated by Django 3.0.5 on 2021-11-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_question_questionimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questionimg',
            field=models.ImageField(default='image/admin.png', null=True, upload_to='image/'),
        ),
    ]
