# Generated by Django 3.0.5 on 2021-11-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20211120_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionimg',
            field=models.ImageField(blank=True, default='image/admin.png', null=True, upload_to='image/questimg/'),
        ),
    ]
