# Generated by Django 3.0.5 on 2021-11-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20211121_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='endtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='starttime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionimg',
            field=models.ImageField(blank=True, default='image/noimage.png', null=True, upload_to='image/'),
        ),
    ]
