# Generated by Django 3.0.5 on 2022-04-05 11:42

from django.db import migrations
from quiz.models import *
import datetime
from random import randrange
import time
import random
def randomTime():
    # generate random number scaled to number of seconds in a day
    # (24*60*60) = 86,400
    
       rtime = int(random.random()*86400)
    
       hours   = int(rtime/3600)
       minutes = int((rtime - hours*3600)/60)
       seconds = rtime - hours*3600 - minutes*60
    
       time_string = '%02d:%02d:%02d' % (hours, minutes, seconds)
       return time_string
       
class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_auto_20220405_1109'),
    ]
    

    
    def gen_uuid(apps, schema_editor):
        
        for row in Meeting.objects.all():
            
            row.end_time=randomTime()
            row.save()
    operations = [

        migrations.RunPython(gen_uuid),
        migrations.AlterUniqueTogether(
            name='meeting',
            unique_together={('start_time', 'end_time', 'date', 'Course_id')},
        ),
    ]
