# Generated by Django 3.0.5 on 2022-04-06 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_auto_20220405_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='parens_or_not',
        ),
    ]
