# Generated by Django 3.0.5 on 2021-11-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atte_system', '0005_auto_20201209_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questionimg',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
