# Generated by Django 3.0.5 on 2021-11-20 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atte_system', '0006_question_questionimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questionimg',
        ),
    ]
