# Generated by Django 3.0.5 on 2021-11-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atte_system', '0008_question_questionimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionimg',
            field=models.ImageField(default='image/admin.png', upload_to='image/'),
        ),
    ]
