# Generated by Django 3.0.5 on 2021-11-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atte_system', '0012_auto_20211121_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionimg',
            field=models.ImageField(blank=True, default='image/admin.png', null=True, upload_to='image/'),
        ),
    ]
