# Generated by Django 3.0.5 on 2021-11-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atte_system', '0014_course_totaltime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(),
        ),
    ]
