# Generated by Django 3.0.5 on 2021-11-21 15:07

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('Atte_system', '0016_auto_20211121_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
