# Generated by Django 3.0.5 on 2022-04-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atte_system', '0021_auto_20220404_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='question_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_marks',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Course_id',
        ),
        migrations.AddField(
            model_name='teacher',
            name='Course_id',
            field=models.ManyToManyField(blank=True, null=True, to='Atte_system.Course'),
        ),
    ]
