# Generated by Django 3.0.5 on 2022-04-05 03:58

from django.db import migrations, models
import uuid
from Atte_system.models import *
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('Atte_system', '0022_auto_20220404_2146'),
    ]
    def gen_uuid(apps, schema_editor):
        for row in Course.objects.all():
            row.join_code = uuid.uuid4()
            row.save()

    operations = [
         
        migrations.AddField(
            model_name='course',
            name='join_code',
            field=models.UUIDField(default=uuid.uuid4),
             preserve_default=True,
        ),
        migrations.RunPython(gen_uuid),
         migrations.AlterField(
            model_name='course',
            name='join_code',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
        
    ]
