# Generated by Django 3.0.5 on 2022-04-05 05:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Atte_system', '0023_course_join_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='Meeting_link',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='join_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
