# Generated by Django 3.0.5 on 2022-04-03 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atte_system', '0020_auto_20220403_1611'),
        ('student', '0002_remove_student_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
